meta:
  app_id: ocp_quickstart
  display_name: OCP Quickstart
  version: 1.0.0-dev.3
  vendor: optimizely
  summary: Sync offline store orders and customer data into ODP
  support_url: https://www.acme.com/
  contact_email: me@acme.com
  categories:
    - Testing & Utilities
  availability:
    - us

runtime: node18

functions:
  storage_event:
    entry_point: StorageEventHandler
    description: Handles events received from Azure EventGrid.
